In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [7]:
print(type(df))
print(type(df['a']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [9]:
list(df['a'])

[1, 5, 9]

In [11]:
df.head()

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [13]:
df.tail(2)

   a   b   c   d message
1  5   6   7   8   world
2  9  10  11  12     foo

In [15]:
df  = pd.read_table('test.tsv')
df

    t   t1   t2  t3
0  af  afa  afa  af
1  sa  san  san  sa

In [17]:
df  = pd.read_csv('test.tsv', sep='\t')
df

    t   t1   t2  t3
0  af  afa  afa  af
1  sa  san  san  sa

In [19]:
df  = pd.read_table('ex1.csv', sep=',', header=None, names=['col1', 'col2', 'col3', 'col4' , 'col5', 'col6'])
df

  col1 col2 col3 col4     col5  col6
0    a    b    c    d  message   NaN
1    1    2    3    4    hello   NaN
2    5    6    7    8    world   NaN
3    9   10   11   12      foo   NaN

In [21]:
# header - no header (None), infer (consider first row header - default)
# sep
# names =array of col names if header is None
df  = pd.read_table('ex1.csv', sep=',', header=None, names=['col1', 'col2', 'col3', ])
df

     col1 col2     col3
a b     c    d  message
1 2     3    4    hello
5 6     7    8    world
9 10   11   12      foo

In [23]:
# usecols - pick a column
df  = pd.read_table('ex1.csv', sep=',', header=None, names=['col1', 'col2', 'col3', 'col4', 'col5'], usecols=['col1', 'col2'])
df

  col1 col2
0    a    b
1    1    2
2    5    6
3    9   10

In [25]:
# index_col - column index for grouping - uniquely identify rows --- MultiIndex
p = pd.read_csv('ex2.csv', index_col=['key1', 'key2'])
p

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     c          7       8
two  a          9      10
     b         11      12
     c         13      14
     c         15      16

In [27]:
p.index

MultiIndex([('one', 'a'),
            ('one', 'b'),
            ('one', 'c'),
            ('one', 'c'),
            ('two', 'a'),
            ('two', 'b'),
            ('two', 'c'),
            ('two', 'c')],
           names=['key1', 'key2'])

In [29]:
# skiprows - To skip the rows
pd.read_csv('ex2.csv', skiprows=[2,3])

  key1 key2  value1  value2
0  one    a       1       2
1  one    c       7       8
2  two    a       9      10
3  two    b      11      12
4  two    c      13      14
5  two    c      15      16

In [31]:
df = pd.read_csv('ex3.csv')
# pd.isnull(df).sum()
df.isnull()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False     True

In [33]:
pd.read_csv('ex3.csv', na_values=['NULL'])

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [35]:
pd.read_excel('excel.xlsx', sheet_name='Sheet1')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   7   world
2           2  9  10  11  12     foo

In [36]:
ht = pd.read_html('http://basketball-reference.com/leagues/NBA_2015_totals.html')
ht[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [37]:
ht[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [39]:
titanic_train = pd.read_csv("titanic.csv")   
titanic_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [43]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [45]:
titanic_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [47]:
titanic_train[['PassengerId', 'Pclass']]

     PassengerId  Pclass
0            892       3
1            893       3
2            894       2
3            895       3
4            896       3
..           ...     ...
413         1305       3
414         1306       1
415         1307       3
416         1308       3
417         1309       3

[418 rows x 2 columns]

In [49]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [53]:
titanic_train.shape

(418, 12)

In [55]:
pd.read_csv("titanic.csv", nrows=5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [73]:
chunk = pd.read_csv("titanic.csv", chunksize=100)
chunk

In [69]:
for i in chunk:
    print(i)

    PassengerId  Survived  Pclass  \
0           892         0       3
1           893         1       3
2           894         0       2
3           895         0       3
4           896         1       3
..          ...       ...     ...
95          987         0       3
96          988         1       1
97          989         0       3
98          990         1       3
99          991         0       3

                                                 Name     Sex   Age  SibSp  \
0                                    Kelly, Mr. James    male  34.5      0
1                    Wilkes, Mrs. James (Ellen Needs)  female  47.0      1
2                           Myles, Mr. Thomas Francis    male  62.0      0
3                                    Wirz, Mr. Albert    male  27.0      0
4        Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1
..                                                ...     ...   ...    ...
95                         Tenglin, Mr. Gunnar Isidor    male  25.0      0
96  Cavendish, Mrs. Tyrell William (Julia Florence...  female  76.0      1
97                          Makinen, Mr. Kalle Edvard    male  29.0      0
98                       Braf, Miss. Elin Ester Maria  female  20.0      0
99                       Nancarrow, Mr. William Henry    male  33.0      0

    Parch             Ticket     Fare Cabin Embarked
0       0             330911   7.8292   NaN        Q
1       0             363272   7.0000   NaN        S
2       0             240276   9.6875   NaN        Q
3       0             315154   8.6625   NaN        S
4       1            3101298  12.2875   NaN        S
..    ...                ...      ...   ...      ...
95      0             350033   7.7958   NaN        S
96      0              19877  78.8500   C46        S
97      0  STON/O 2. 3101268   7.9250   NaN        S
98      0             347471   7.8542   NaN        S
99      0         A./5. 3338   8.0500   NaN        S

[100 rows x 12 columns]
     PassengerId  Survived  Pclass  \
100          992         1       1
101          993         0       2
102          994         0       3
103          995         0       3
104          996         1       3
..           ...       ...     ...
195         1087         0       3
196         1088         0       1
197         1089         1       3
198         1090         0       2
199         1091         1       3

                                                  Name     Sex   Age  SibSp  \
100  Stengel, Mrs. Charles Emil Henry (Annie May Mo...  female  43.0      1
101                                 Weisz, Mr. Leopold    male  27.0      1
102                                 Foley, Mr. William    male   NaN      0
103             Johansson Palmquist, Mr. Oskar Leander    male  26.0      0
104          Thomas, Mrs. Alexander (Thamine Thelma")"  female  16.0      1
..                                                 ...     ...   ...    ...
195                  Karlsson, Mr. Julius Konrad Eugen    male  33.0      0
196                    Spedden, Master. Robert Douglas    male   6.0      0
197                        Nilsson, Miss. Berta Olivia  female  18.0      0
198                     Baimbrigge, Mr. Charles Robert    male  23.0      0
199            Rasmussen, Mrs. (Lena Jacobsen Solvang)  female   NaN      0

     Parch      Ticket      Fare Cabin Embarked
100      0       11778   55.4417  C116        C
101      0      228414   26.0000   NaN        S
102      0      365235    7.7500   NaN        Q
103      0      347070    7.7750   NaN        S
104      1        2625    8.5167   NaN        C
..     ...         ...       ...   ...      ...
195      0      347465    7.8542   NaN        S
196      2       16966  134.5000   E34        C
197      0      347066    7.7750   NaN        S
198      0  C.A. 31030   10.5000   NaN        S
199      0       65305    8.1125   NaN        S

[100 rows x 12 columns]
     PassengerId  Survived  Pclass                                     Name  \
200         1092         1       3                       Murphy, Miss. Nora
201         1093         0       3  Danbom, Master. Gilbert Sigvard Emanuel
202         1094         0       1                   Astor, Col. John Jacob
203         1095         1       2               Quick, Miss. Winifred Vera
204         1096         0       2                 Andrew, Mr. Frank Thomas
..           ...       ...     ...                                      ...
295         1187         0       3                     Angheloff, Mr. Minko
296         1188         1       2                    Laroche, Miss. Louise
297         1189         0       3                        Samaan, Mr. Hanna
298         1190         0       1               Loring, Mr. Joseph Holland
299         1191         0       3                      Johansson, Mr. Nils

        Sex    Age  SibSp  Parch         Ticket      Fare    Cabin Embarked
200  female    NaN      0      0          36568   15.5000      NaN        Q
201    male   0.33      0      2         347080   14.4000      NaN        S
202    male  47.00      1      0       PC 17757  227.5250  C62 C64        C
203  female   8.00      1      1          26360   26.0000      NaN        S
204    male  25.00      0      0     C.A. 34050   10.5000      NaN        S
..      ...    ...    ...    ...            ...       ...      ...      ...
295    male  26.00      0      0         349202    7.8958      NaN        S
296  female   1.00      1      2  SC/Paris 2123   41.5792      NaN        C
297    male    NaN      2      0           2662   21.6792      NaN        C
298    male  30.00      0      0         113801   45.5000      NaN        S
299    male  29.00      0      0         347467    7.8542      NaN        S

[100 rows x 12 columns]
     PassengerId  Survived  Pclass  \
300         1192         0       3
301         1193         0       2
302         1194         0       2
303         1195         0       3
304         1196         1       3
..           ...       ...     ...
395         1287         1       1
396         1288         0       3
397         1289         1       1
398         1290         0       3
399         1291         0       3

                                                  Name     Sex   Age  SibSp  \
300                          Olsson, Mr. Oscar Wilhelm    male  32.0      0
301                                Malachard, Mr. Noel    male   NaN      0
302                        Phillips, Mr. Escott Robert    male  43.0      0
303                                  Pokrnic, Mr. Tome    male  24.0      0
304                  McCarthy, Miss. Catherine Katie""  female   NaN      0
..                                                 ...     ...   ...    ...
395     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)  female  18.0      1
396                               Colbert, Mr. Patrick    male  24.0      0
397  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...  female  48.0      1
398                     Larsson-Rondberg, Mr. Edvard A    male  22.0      0
399                           Conlon, Mr. Thomas Henry    male  31.0      0

     Parch       Ticket     Fare Cabin Embarked
300      0       347079   7.7750   NaN        S
301      0       237735  15.0458     D        C
302      1  S.O./P.P. 2  21.0000   NaN        S
303      0       315092   8.6625   NaN        S
304      0       383123   7.7500   NaN        Q
..     ...          ...      ...   ...      ...
395      0        13695  60.0000   C31        S
396      0       371109   7.2500   NaN        Q
397      1        13567  79.2000   B41        C
398      0       347065   7.7750   NaN        S
399      0        21332   7.7333   NaN        Q

[100 rows x 12 columns]
     PassengerId  Survived  Pclass  \
400         1292         1       1
401         1293         0       2
402         1294         1       1
403         1295         0       1
404         1296         0       1
405         1297         0       2
406         1298         0       2
407         1299         0       1
408         1300         1       3
409         1301         1       3
410         1302         1       3
411         1303         1       1
412         1304         1       3
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                                Name     Sex   Age  SibSp  \
400                          Bonnell, Miss. Caroline  female  30.0      0
401                                  Gale, Mr. Harry    male  38.0      1
402                   Gibson, Miss. Dorothy Winifred  female  22.0      0
403                           Carrau, Mr. Jose Pedro    male  17.0      0
404                     Frauenthal, Mr. Isaac Gerald    male  43.0      1
405     Nourney, Mr. Alfred (Baron von Drachstedt")"    male  20.0      0
406                        Ware, Mr. William Jeffery    male  23.0      1
407                       Widener, Mr. George Dunton    male  50.0      1
408                  Riordan, Miss. Johanna Hannah""  female   NaN      0
409                        Peacock, Miss. Treasteall  female   3.0      1
410                           Naughton, Miss. Hannah  female   NaN      0
411  Minahan, Mrs. William Edward (Lillian E Thorpe)  female  37.0      1
412                   Henriksson, Miss. Jenny Lovisa  female  28.0      0
413                               Spector, Mr. Woolf    male   NaN      0
414                     Oliva y Ocana, Dona. Fermina  female  39.0      0
415                     Saether, Mr. Simon Sivertsen    male  38.5      0
416                              Ware, Mr. Frederick    male   NaN      0
417                         Peter, Master. Michael J    male   NaN      1

     Parch              Ticket      Fare Cabin Embarked
400      0               36928  164.8667    C7        S
401      0               28664   21.0000   NaN        S
402      1              112378   59.4000   NaN        C
403      0              113059   47.1000   NaN        S
404      0               17765   27.7208   D40        C
405      0       SC/PARIS 2166   13.8625   D38        C
406      0               28666   10.5000   NaN        S
407      1              113503  211.5000   C80        C
408      0              334915    7.7208   NaN        Q
409      1  SOTON/O.Q. 3101315   13.7750   NaN        S
410      0              365237    7.7500   NaN        Q
411      0               19928   90.0000   C78        Q
412      0              347086    7.7750   NaN        S
413      0           A.5. 3236    8.0500   NaN        S
414      0            PC 17758  108.9000  C105        C
415      0  SOTON/O.Q. 3101262    7.2500   NaN        S
416      0              359309    8.0500   NaN        S
417      1                2668   22.3583   NaN        C

In [75]:
chunk.read()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [81]:
df = pd.read_csv('ex3.csv')
df.to_csv('out.csv', sep='@')
# to_exec

In [85]:
import sys
df.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,NULL

In [91]:
df = pd.read_csv('ex3.csv')
# index and header removed
df.to_csv('out.csv', index = False, header = False)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [93]:
df = pd.read_csv('ex3.csv')
# pick specific columns
df.to_csv('out.csv',  columns=['a','b'])

# Date

In [116]:
dates = pd.date_range(start='1/1/2000', periods=7, freq='ME')

In [120]:
import numpy as np
ts = pd.Series(np.arange(7), index = dates)
ts

2000-01-31    0
2000-02-29    1
2000-03-31    2
2000-04-30    3
2000-05-31    4
2000-06-30    5
2000-07-31    6
Freq: ME, dtype: int32

In [126]:
ts.to_csv('date.csv', header=False)
# !cat date.csv # only in linux
!type date.csv

2000-01-31,0
2000-02-29,1
2000-03-31,2
2000-04-30,3
2000-05-31,4
2000-06-30,5
2000-07-31,6

In [152]:
import csv
r = csv.reader(open('ex1.csv'))
# for i in r:
#     print(i)
list(r)

[['a', 'b', 'c', 'd', 'message'],
 ['1', '2', '3', '4', 'hello'],
 ['5', '6', '7', '8', 'world'],
 ['9', '10', '11', '12', 'foo']]

In [140]:
r.line_num

4

In [156]:
with open('ex1.csv') as f:
    r = list(csv.reader(f))
r

[['a', 'b', 'c', 'd', 'message'],
 ['1', '2', '3', '4', 'hello'],
 ['5', '6', '7', '8', 'world'],
 ['9', '10', '11', '12', 'foo']]

In [158]:
header, val = r[0], r[1:]

In [186]:
dic = {h:v for h, v in zip(header, zip(*val))}
dic

{'a': ('1', '5', '9'),
 'b': ('2', '6', '10'),
 'c': ('3', '7', '11'),
 'd': ('4', '8', '12'),
 'message': ('hello', 'world', 'foo')}

In [188]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [194]:
import json
r = json.loads(obj)
r

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [196]:
json.dumps(r)

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

In [204]:
pd.DataFrame(r['siblings'], columns=['name', 'age', 'pets'], index =['1', '2'])

    name  age                    pets
1  Scott   30            [Zeus, Zuko]
2  Katie   38  [Sixes, Stache, Cisco]

In [224]:
a = pd.read_json('a.json')
a

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [234]:
print(a.to_json())
a.to_json(orient='records')

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

'[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]'

In [240]:
ht = pd.read_html('htm.html')
ht[0]

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"
...,...,...,...,...,...,...,...
542,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB","July 27, 2001","August 19, 2014"
543,Malta National Bank,Malta,OH,6629,North Valley Bank,"May 3, 2001","November 18, 2002"
544,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,"February 2, 2001","February 18, 2003"
545,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,"December 14, 2000","March 17, 2005"
546,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,"October 13, 2000","March 17, 2005"

In [242]:
print(len(ht))

1

In [246]:
tm = pd.to_datetime(ht[0]['Closing Date'])
tm.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, dtype: int64

In [250]:
tm[0].date().day

23

# Binary Format Data

In [261]:
data = pd.read_csv('ex1.csv')
data.to_pickle('pickle')
pd.read_pickle('pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [263]:
# HDF5 Format
s = pd.HDFStore('my.h5')
s

<class 'pandas.io.pytables.HDFStore'>
File path: my.h5

# Web API

In [273]:
import requests
res = requests.get('https://api.github.com/repos/pandas-dev/pandas/issues')
res =res.json()
res

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/59660',
  'id': 2496588305,
  'node_id': 'PR_kwDOAA0YD8558Ms4',
  'number': 59660,
  'title': 'DOC: fix SA01,ES01 for pandas.NaT',
  'user': {'login': 'tuhinsharma121',
   'id': 6801780,
   'node_id': 'MDQ6VXNlcjY4MDE3ODA=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6801780?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/tuhinsharma121',
   'html_url': 'https://github.com/tuhinsharma121',
   'followers_url': 'https://api.github.com/users/tuhinsharma121/followers',
   'following_url': 'https://api.github.com/users/tuhinsharma121/following{/other_user}',
   'gists_url': 'https://api.github.com/users/tuhinsharma121/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/tuhinsharma121/subscriptions',
   'organizations_url': 'https://api.github.com/users/tuhinsharma121/orgs',
   'repos_url': 'https://api.github.com/users/tuhinsharma121/repos',
   'events_url': 'https://api.github.com/users/tuhinsharma121/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/tuhinsharma121/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-08-30T08:33:22Z',
  'updated_at': '2024-08-30T08:33:22Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'draft': True,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59660',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/59660',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/59660.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/59660.patch',
   'merged_at': None},
  'body': 'fixes\r\n\r\n```\r\npandas.NaT SA01,ES01\r\n```',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59659',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59659/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59659/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59659/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/59659',
  'id': 2496553230,
  'node_id': 'I_kwDOAA0YD86UzmEO',
  'number': 59659,
  'title': 'ENH: increase verbosity on error',
  'user': {'login': 'romeokienzler',
   'id': 5694071,
   'node_id': 'MDQ6VXNlcjU2OTQwNzE=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/5694071?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/romeokienzler',
   'html_url': 'https://github.com/romeokienzler',
   'followers_url': 'https://api.github.com/users/romeokienzler/followers',
   'following_url': 'https://api.github.com/users/romeokienzler/following{/other_user}',
   'gists_url': 'https://api.github.com/users/romeokienzler/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/romeokienzler/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/romeokienzler/subscriptions',
   'organizations_url': 'https://api.github.com/users/romeokienzler/orgs',
   'repos_url': 'https://api.github.com/users/romeokienzler/repos',
   'events_url': 'https://api.github.com/users/romeokienzler/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/romeokienzler/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76812,
    'node_id': 'MDU6TGFiZWw3NjgxMg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',
    'name': 'Enhancement',
    'color': '4E9A06',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-08-30T08:16:31Z',
  'updated_at': '2024-08-30T08:16:31Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': '### Feature Type\n\n- [ ] Adding new functionality to pandas\n\n- [X] Changing existing functionality in pandas\n\n- [ ] Removing existing functionality in pandas\n\n\n### Problem Description\n\nOn a specific type error the error causing type is not logged in the error\n\n### Feature Description\n\nBy replacing:\r\n`raise AttributeError("Can only use .str accessor with string values!")`\r\nwith\r\n`raise AttributeError(f"Can only use .str accessor with string values! Inferred dType: {inferred_dtype}")`\r\nthe problem would be solved\r\n\r\nDetails can be found in [here](https://github.com/pandas-dev/pandas/pull/59649/files)\n\n### Alternative Solutions\n\nUse a debugger and set a break point\n\n### Additional Context\n\n_No response_',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59659/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59659/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59658',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59658/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59658/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59658/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/59658',
  'id': 2496546114,
  'node_id': 'PR_kwDOAA0YD8558DV3',
  'number': 59658,
  'title': 'DOC: fix RT03,SA01,ES01 for pandas.MultiIndex.reorder_levels',
  'user': {'login': 'tuhinsharma121',
   'id': 6801780,
   'node_id': 'MDQ6VXNlcjY4MDE3ODA=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6801780?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/tuhinsharma121',
   'html_url': 'https://github.com/tuhinsharma121',
   'followers_url': 'https://api.github.com/users/tuhinsharma121/followers',
   'following_url': 'https://api.github.com/users/tuhinsharma121/following{/other_user}',
   'gists_url': 'https://api.github.com/users/tuhinsharma121/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/tuhinsharma121/subscriptions',
   'organizations_url': 'https://api.github.com/users/tuhinsharma121/orgs',
   'repos_url': 'https://api.github.com/users/tuhinsharma121/repos',
   'events_url': 'https://api.github.com/users/tuhinsharma121/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/tuhinsharma121/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-08-30T08:12:46Z',
  'updated_at': '2024-08-30T08:12:46Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'draft': True,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59658',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/59658',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/59658.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/59658.patch',
   'merged_at': None},
  'body': 'fixes\r\n\r\n```\r\npandas.MultiIndex.reorder_levels RT03,SA01,ES01\r\n```',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59658/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59658/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59657',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59657/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59657/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59657/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/59657',
  'id': 2496456912,
  'node_id': 'I_kwDOAA0YD86UzOjQ',
  'number': 59657,
  'title': 'PERF: Melt 2x slower when future.infer_string option enabled',
  'user': {'login': 'maver1ck',
   'id': 4006010,
   'node_id': 'MDQ6VXNlcjQwMDYwMTA=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/4006010?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/maver1ck',
   'html_url': 'https://github.com/maver1ck',
   'followers_url': 'https://api.github.com/users/maver1ck/followers',
   'following_url': 'https://api.github.com/users/maver1ck/following{/other_user}',
   'gists_url': 'https://api.github.com/users/maver1ck/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/maver1ck/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/maver1ck/subscriptions',
   'organizations_url': 'https://api.github.com/users/maver1ck/orgs',
   'repos_url': 'https://api.github.com/users/maver1ck/repos',
   'events_url': 'https://api.github.com/users/maver1ck/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/maver1ck/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 8935311,
    'node_id': 'MDU6TGFiZWw4OTM1MzEx',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance',
    'name': 'Performance',
    'color': 'a10c02',
    'default': False,
    'description': 'Memory or execution speed performance'},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-08-30T07:27:56Z',
  'updated_at': '2024-08-30T07:29:22Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': '### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this issue exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```\r\nimport pandas as pd\r\nimport numpy as np\r\n\r\n# This configuration option makes this code slow\r\npd.options.future.infer_string = True\r\n\r\n# Define dimensions\r\nn_rows = 10000\r\nn_cols = 10000\r\n\r\n# Generate random IDs for the rows\r\nids = [f"string_id_{i}" for i in range(1, n_rows + 1)]\r\n\r\n# Generate a random sparse matrix with 10% non-NaN values\r\ndata = np.random.choice([np.nan, 1], size=(n_rows, n_cols), p=[0.9, 0.1])\r\n\r\n# Create a DataFrame from the sparse matrix and add the \'Id\' column\r\ndf = pd.DataFrame(data, columns=[f"column_name_{i}" for i in range(1, n_cols + 1)])\r\ndf.insert(0, \'Id\', ids)\r\n\r\n# Melt the DataFrame\r\ndf_melted = df.melt(id_vars=[\'Id\'], var_name=\'Column\', value_name=\'Value\')\r\n\r\n# Display the first few rows of the melted DataFrame\r\ndf_melted.head()\r\n```\n\n### Installed Versions\n\n```\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140\r\npython                : 3.12.5.final.0\r\npython-bits           : 64\r\nOS                    : Darwin\r\nOS-release            : 23.6.0\r\nVersion               : Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000\r\nmachine               : arm64\r\nprocessor             : arm\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : pl_PL.UTF-8\r\nLOCALE                : pl_PL.UTF-8\r\n\r\npandas                : 2.2.2\r\nnumpy                 : 2.1.0\r\npytz                  : 2024.1\r\ndateutil              : 2.9.0.post0\r\nsetuptools            : 73.0.1\r\npip                   : 24.1.2\r\nCython                : None\r\npytest                : 8.3.2\r\nhypothesis            : None\r\nsphinx                : None\r\nblosc                 : None\r\nfeather               : None\r\nxlsxwriter            : None\r\nlxml.etree            : None\r\nhtml5lib              : None\r\npymysql               : None\r\npsycopg2              : None\r\njinja2                : 3.1.4\r\nIPython               : 8.26.0\r\npandas_datareader     : None\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.3\r\nbottleneck            : None\r\ndataframe-api-compat  : None\r\nfastparquet           : None\r\nfsspec                : 2024.6.1\r\ngcsfs                 : None\r\nmatplotlib            : None\r\nnumba                 : None\r\nnumexpr               : None\r\nodfpy                 : None\r\nopenpyxl              : None\r\npandas_gbq            : None\r\npyarrow               : 17.0.0\r\npyreadstat            : None\r\npython-calamine       : None\r\npyxlsb                : None\r\ns3fs                  : 2024.6.1\r\nscipy                 : None\r\nsqlalchemy            : None\r\ntables                : None\r\ntabulate              : None\r\nxarray                : None\r\nxlrd                  : None\r\nzstandard             : None\r\ntzdata                : 2024.1\r\nqtpy                  : None\r\npyqt5                 : None\r\n```\r\n\n\n### Prior Performance\n\nThis code with `pd.options.future.infer_string = False` runs in:\r\n`5.23 s ± 1.35 s per loop (mean ± std. dev. of 7 runs, 1 loop each)`\r\nMemory consumption is around 14 GB.\r\n\r\nEnabling `pd.options.future.infer_string = True` makes it 2 times slower:\r\n`10.6 s ± 40.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`\r\nAlso memory consumption is bigger with peak around 25GB.',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59657/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59657/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59656',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59656/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59656/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59656/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/59656',
  'id': 2495918748,
  'node_id': 'I_kwDOAA0YD86UxLKc',
  'number': 59656,
  'title': 'BUG: arithmetic between datetime.timedelta scalar and series produces timedelta64[us] instead of timedelta64[ns]',
  'user': {'login': 'sfc-gh-mvashishtha',
   'id': 149194323,
   'node_id': 'U_kgDOCOSGUw',
   'avatar_url': 'https://avatars.githubusercontent.com/u/149194323?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/sfc-gh-mvashishtha',
   'html_url': 'https://github.com/sfc-gh-mvashishtha',
   'followers_url': 'https://api.github.com/users/sfc-gh-mvashishtha/followers',
   'following_url': 'https://api.github.com/users/sfc-gh-mvashishtha/following{/other_user}',
   'gists_url': 'https://api.github.com/users/sfc-gh-mvashishtha/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/sfc-gh-mvashishtha/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/sfc-gh-mvashishtha/subscriptions',
   'organizations_url': 'https://api.github.com/users/sfc-gh-mvashishtha/orgs',
   'repos_url': 'https://api.github.com/users/sfc-gh-mvashishtha/repos',
   'events_url': 'https://api.github.com/users/sfc-gh-mvashishtha/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/sfc-gh-mvashishtha/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-08-30T01:02:35Z',
  'updated_at': '2024-08-30T01:02:35Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,

In [283]:
res[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660/events',
 'html_url': 'https://github.com/pandas-dev/pandas/pull/59660',
 'id': 2496588305,
 'node_id': 'PR_kwDOAA0YD8558Ms4',
 'number': 59660,
 'title': 'DOC: fix SA01,ES01 for pandas.NaT',
 'user': {'login': 'tuhinsharma121',
  'id': 6801780,
  'node_id': 'MDQ6VXNlcjY4MDE3ODA=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/6801780?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/tuhinsharma121',
  'html_url': 'https://github.com/tuhinsharma121',
  'followers_url': 'https://api.github.com/users/tuhinsharma121/followers',
  'following_url': 'https://api.github.com/users/tuhinsharma121/following{/other_user}',
  'gists_url': 'https://api.github.com/users/tuhinsharma121/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/tuhinsharma121/subscriptions',
  'organizations_url': 'https://api.github.com/users/tuhinsharma121/orgs',
  'repos_url': 'https://api.github.com/users/tuhinsharma121/repos',
  'events_url': 'https://api.github.com/users/tuhinsharma121/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/tuhinsharma121/received_events',
  'type': 'User',
  'site_admin': False},
 'labels': [],
 'state': 'open',
 'locked': False,
 'assignee': None,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2024-08-30T08:33:22Z',
 'updated_at': '2024-08-30T08:33:22Z',
 'closed_at': None,
 'author_association': 'CONTRIBUTOR',
 'active_lock_reason': None,
 'draft': True,
 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59660',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/59660',
  'diff_url': 'https://github.com/pandas-dev/pandas/pull/59660.diff',
  'patch_url': 'https://github.com/pandas-dev/pandas/pull/59660.patch',
  'merged_at': None},
 'body': 'fixes\r\n\r\n```\r\npandas.NaT SA01,ES01\r\n```',
 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660/reactions',
  'total_count': 0,
  '+1': 0,
  '-1': 0,
  'laugh': 0,
  'hooray': 0,
  'confused': 0,
  'heart': 0,
  'rocket': 0,
  'eyes': 0},
 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59660/timeline',
 'performed_via_github_app': None,
 'state_reason': None}

In [285]:
pd.DataFrame(res, columns=['number', 'title', 'labels', 'state'])

,number,title,labels,state
0,59660,"DOC: fix SA01,ES01 for pandas.NaT",[],open
1,59659,ENH: increase verbosity on error,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
2,59658,"DOC: fix RT03,SA01,ES01 for pandas.MultiIndex....",[],open
3,59657,PERF: Melt 2x slower when future.infer_string ...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
4,59656,BUG: arithmetic between datetime.timedelta sca...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
5,59655,DOCS: fix docstring validation error for panda...,[],open
6,59654,expose `to_pandas_kwargs` in `read_parquet` wi...,[],open
7,59653,BUG: some cases of binary arithmetic between s...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
8,59652,BUG: Pearson correlation outside expected rang...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
9,59650,BUG: diff method incorrect on datetime64[s],"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
10,59649,increase verbosity,[],open
11,59648,TST: Add SparseArray _arith_method test to fai...,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
12,59647,PERF: CategoricalDtype.update_dtype,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
13,59646,BUG: Retain index when merging on an index,[],open
14,59636,Fix binary operations on attrs for Series and ...,[],open
15,59631,ENH: support the Arrow PyCapsule Interface for...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
16,59629,BUG: Fix inconsistent pivot table subaggregati...,[],open
17,59627,BUG(?): Allow setitem to category/sparse of th...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
18,59624,API: str.center with pyarrow-backed string dtype,[],open
19,59623,BUG: style.map() not compatible with CSS strin...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
20,59620,"BUG: Resampling to ""B"" frequency with closed=""...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
21,59619,REF: Use range over arange for iterators,"[{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
22,59616,String dtype: propagate NaNs as False in predi...,"[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
23,59615,DEPR (string): non-bool na for obj.str.contains,"[{'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUy...",open
24,59614,BUG: `numpy.ma.fix_invalid` makes changes in-p...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
25,59612,2.3 release dates,[],open
26,59609,BUG: isin check with numpy array works incorre...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
27,59601,Fix/group by agg pyarrow bool numpy same type,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
28,59595,DOCS: fix docstring validation errors for pand...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
29,59592,DOC: fix docstring validation errors for panda...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open